web:
  build:  .
  environment:
    XDEBUG_CONFIG: "remote_host=192.168.5.77"
    PHP_IDE_CONFIG: "serverName=my.local"
  ports:
    - "80:3000"
  links:
    - db
db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: pipe
    MYSQL_USER: pipe
    MYSQL_PASSWORD: pipe