web:
  build:  .
  environment:
    DB_HOSTNAME: "db"
  ports:
    - "80:3000"
  links:
    - db
db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: pipe
    MYSQL_USER: pipe
    MYSQL_PASSWORD: pipe